version: '3.7'

services:
  front:
    build: ./packages/front
    ports:
      - 80:1234
    volumes:
      - ./packages/front/src:/app/src

  api:
    build: ./packages/api
    ports:
      - 8080:8080
